/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayletTestJNI */

#ifndef _Included_ArrayletTestJNI
#define _Included_ArrayletTestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayletTestJNI
 * Method:    testPrimitiveArrayCriticalArraylets
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_ArrayletTestJNI_testPrimitiveArrayCriticalArraylets
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
