/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayletTestJNI */

#ifndef _Included_ArrayletTestJNI
#define _Included_ArrayletTestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayletTestJNI
 * Method:    testPrimitiveArrayCriticalArraylets
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_ArrayletTestJNI_testPrimitiveArrayCriticalArraylets___3DI
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     ArrayletTestJNI
 * Method:    testPrimitiveArrayCriticalArraylets
 * Signature: ([CI)V
 */
JNIEXPORT void JNICALL Java_ArrayletTestJNI_testPrimitiveArrayCriticalArraylets___3CI
  (JNIEnv *, jobject, jcharArray, jint);

/*
 * Class:     ArrayletTestJNI
 * Method:    testStringCriticalArraylets
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ArrayletTestJNI_testStringCriticalArraylets
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
